{% set name = "kedro-boot" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/takikadiri/kedro-boot/archive/{{ version }}.tar.gz
  sha256: 73e34892f2bb3108b2b306af30c71aab0766989bbb1c9716940ed452a4c46670

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - kedro >=0.19.1,<0.20.0

test:
  imports:
    - kedro_boot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/takikadiri/kedro-boot
  summary: A kedro plugin that streamlines the integration between Kedro projects and external applications, making it easier for you to develop production-ready data science applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
